// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.util.datastructures;

import net.minecraft.util.math.BlockPos;
import java.util.HashSet;
import java.util.Set;

/**
 * Naive implementation of IBlockPosSet, basically just a wrapper around a HashSet<BlockPos>.
 * Used for testing purposes only.
 */
public class NaiveBlockPosSet implements IBlockPosSet {
    private final Set<BlockPos> blockPosSet;

    public NaiveBlockPosSet() {
        this.blockPosSet = new HashSet<>();
    }

    @Override
    public boolean add(int x, int y, int z) {
        return blockPosSet.add(new BlockPos(x, y, z));
    }

    @Override
    public boolean remove(int x, int y, int z) {
        return blockPosSet.remove(new BlockPos(x, y, z));
    }

    @Override
    public boolean contains(int x, int y, int z) {
        return blockPosSet.contains(new BlockPos(x, y, z));
    }

    @Override
    public boolean canStore(int x, int y, int z) {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    public int size() {
        return this.blockPosSet.size();
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEmpty() {
        return this.blockPosSet.isEmpty();
    }

    @java.lang.SuppressWarnings("all")
    public boolean contains(final java.lang.Object arg0) {
        return this.blockPosSet.contains(arg0);
    }

    @java.lang.SuppressWarnings("all")
    public java.lang.Object[] toArray() {
        return this.blockPosSet.toArray();
    }

    @java.lang.SuppressWarnings("all")
    public <T extends java.lang.Object> T[] toArray(final T[] arg0) {
        return this.blockPosSet.<T>toArray(arg0);
    }

    @java.lang.SuppressWarnings("all")
    public boolean remove(final java.lang.Object arg0) {
        return this.blockPosSet.remove(arg0);
    }

    @java.lang.SuppressWarnings("all")
    public boolean containsAll(final java.util.Collection<?> arg0) {
        return this.blockPosSet.containsAll(arg0);
    }

    @java.lang.SuppressWarnings("all")
    public boolean retainAll(final java.util.Collection<?> arg0) {
        return this.blockPosSet.retainAll(arg0);
    }

    @java.lang.SuppressWarnings("all")
    public boolean removeAll(final java.util.Collection<?> arg0) {
        return this.blockPosSet.removeAll(arg0);
    }

    @java.lang.SuppressWarnings("all")
    public void clear() {
        this.blockPosSet.clear();
    }

    @Override
    public java.util.Iterator<BlockPos> iterator() {
        return this.blockPosSet.iterator();
    }
}
