// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships.ship_world;

import org.valkyrienskies.mod.common.ships.QueryableShipData;
import org.valkyrienskies.mod.common.ships.chunk_claims.ShipChunkAllocator;

public class VSWorldData {
    private final QueryableShipData queryableShipData = new QueryableShipData();
    private final ShipChunkAllocator shipChunkAllocator = new ShipChunkAllocator();

    @java.lang.SuppressWarnings("all")
    public QueryableShipData getQueryableShipData() {
        return this.queryableShipData;
    }

    @java.lang.SuppressWarnings("all")
    public ShipChunkAllocator getShipChunkAllocator() {
        return this.shipChunkAllocator;
    }
}
