// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.entity;

import org.joml.Vector3dc;
import org.valkyrienskies.mod.common.ships.ShipData;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * This class stores data about the last ship an entity touched, as well as the velocity that ship added to the entity.
 */
public final class EntityShipMovementData {
    // If null, then the last touched "Ship" was the world. Otherwise, the last touched ship was a real ship.
    @Nullable
    private final ShipData lastTouchedShip;
    private final int ticksSinceTouchedShip;
    // The number of consecutive ticks that lastTouchedShip has equaled null.
    private final int ticksPartOfGround;
    
    @Nonnull
    private final Vector3dc addedLinearVelocity;
    private final double addedYawVelocity;

    @java.lang.SuppressWarnings("all")
    public EntityShipMovementData(@Nullable final ShipData lastTouchedShip, final int ticksSinceTouchedShip, final int ticksPartOfGround,  @Nonnull final Vector3dc addedLinearVelocity, final double addedYawVelocity) {
        if (addedLinearVelocity == null) {
            throw new java.lang.NullPointerException("addedLinearVelocity is marked non-null but is null");
        }
        this.lastTouchedShip = lastTouchedShip;
        this.ticksSinceTouchedShip = ticksSinceTouchedShip;
        this.ticksPartOfGround = ticksPartOfGround;
        this.addedLinearVelocity = addedLinearVelocity;
        this.addedYawVelocity = addedYawVelocity;
    }

    @Nullable
    @java.lang.SuppressWarnings("all")
    public ShipData getLastTouchedShip() {
        return this.lastTouchedShip;
    }

    @java.lang.SuppressWarnings("all")
    public int getTicksSinceTouchedShip() {
        return this.ticksSinceTouchedShip;
    }

    @java.lang.SuppressWarnings("all")
    public int getTicksPartOfGround() {
        return this.ticksPartOfGround;
    }

    
    @Nonnull
    @java.lang.SuppressWarnings("all")
    public Vector3dc getAddedLinearVelocity() {
        return this.addedLinearVelocity;
    }

    @java.lang.SuppressWarnings("all")
    public double getAddedYawVelocity() {
        return this.addedYawVelocity;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EntityShipMovementData)) return false;
        final EntityShipMovementData other = (EntityShipMovementData) o;
        final java.lang.Object this$lastTouchedShip = this.getLastTouchedShip();
        final java.lang.Object other$lastTouchedShip = other.getLastTouchedShip();
        if (this$lastTouchedShip == null ? other$lastTouchedShip != null : !this$lastTouchedShip.equals(other$lastTouchedShip)) return false;
        if (this.getTicksSinceTouchedShip() != other.getTicksSinceTouchedShip()) return false;
        if (this.getTicksPartOfGround() != other.getTicksPartOfGround()) return false;
        final java.lang.Object this$addedLinearVelocity = this.getAddedLinearVelocity();
        final java.lang.Object other$addedLinearVelocity = other.getAddedLinearVelocity();
        if (this$addedLinearVelocity == null ? other$addedLinearVelocity != null : !this$addedLinearVelocity.equals(other$addedLinearVelocity)) return false;
        if (java.lang.Double.compare(this.getAddedYawVelocity(), other.getAddedYawVelocity()) != 0) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $lastTouchedShip = this.getLastTouchedShip();
        result = result * PRIME + ($lastTouchedShip == null ? 43 : $lastTouchedShip.hashCode());
        result = result * PRIME + this.getTicksSinceTouchedShip();
        result = result * PRIME + this.getTicksPartOfGround();
        final java.lang.Object $addedLinearVelocity = this.getAddedLinearVelocity();
        result = result * PRIME + ($addedLinearVelocity == null ? 43 : $addedLinearVelocity.hashCode());
        final long $addedYawVelocity = java.lang.Double.doubleToLongBits(this.getAddedYawVelocity());
        result = result * PRIME + (int) ($addedYawVelocity >>> 32 ^ $addedYawVelocity);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "EntityShipMovementData(lastTouchedShip=" + this.getLastTouchedShip() + ", ticksSinceTouchedShip=" + this.getTicksSinceTouchedShip() + ", ticksPartOfGround=" + this.getTicksPartOfGround() + ", addedLinearVelocity=" + this.getAddedLinearVelocity() + ", addedYawVelocity=" + this.getAddedYawVelocity() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public EntityShipMovementData withLastTouchedShip(@Nullable final ShipData lastTouchedShip) {
        return this.lastTouchedShip == lastTouchedShip ? this : new EntityShipMovementData(lastTouchedShip, this.ticksSinceTouchedShip, this.ticksPartOfGround, this.addedLinearVelocity, this.addedYawVelocity);
    }

    @java.lang.SuppressWarnings("all")
    public EntityShipMovementData withTicksSinceTouchedShip(final int ticksSinceTouchedShip) {
        return this.ticksSinceTouchedShip == ticksSinceTouchedShip ? this : new EntityShipMovementData(this.lastTouchedShip, ticksSinceTouchedShip, this.ticksPartOfGround, this.addedLinearVelocity, this.addedYawVelocity);
    }

    @java.lang.SuppressWarnings("all")
    public EntityShipMovementData withTicksPartOfGround(final int ticksPartOfGround) {
        return this.ticksPartOfGround == ticksPartOfGround ? this : new EntityShipMovementData(this.lastTouchedShip, this.ticksSinceTouchedShip, ticksPartOfGround, this.addedLinearVelocity, this.addedYawVelocity);
    }

    @java.lang.SuppressWarnings("all")
    public EntityShipMovementData withAddedLinearVelocity( @Nonnull final Vector3dc addedLinearVelocity) {
        if (addedLinearVelocity == null) {
            throw new java.lang.NullPointerException("addedLinearVelocity is marked non-null but is null");
        }
        return this.addedLinearVelocity == addedLinearVelocity ? this : new EntityShipMovementData(this.lastTouchedShip, this.ticksSinceTouchedShip, this.ticksPartOfGround, addedLinearVelocity, this.addedYawVelocity);
    }

    @java.lang.SuppressWarnings("all")
    public EntityShipMovementData withAddedYawVelocity(final double addedYawVelocity) {
        return this.addedYawVelocity == addedYawVelocity ? this : new EntityShipMovementData(this.lastTouchedShip, this.ticksSinceTouchedShip, this.ticksPartOfGround, this.addedLinearVelocity, addedYawVelocity);
    }
}
