// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.command.converters;

import net.minecraft.command.ICommandSender;
import net.minecraft.world.World;
import org.valkyrienskies.mod.common.ships.QueryableShipData;
import org.valkyrienskies.mod.common.ships.ShipData;
import picocli.CommandLine.ITypeConverter;
import picocli.CommandLine.TypeConversionException;

public class ShipDataConverter implements ITypeConverter<ShipData> {
    private final ICommandSender sender;

    @Override
    public ShipData convert(String value) throws TypeConversionException {
        World world = sender.getEntityWorld();
        QueryableShipData data = QueryableShipData.get(world);
        return data.getShipFromName(value).orElseThrow(() -> new TypeConversionException("That ship, " + value + ", could not be found"));
    }

    @java.lang.SuppressWarnings("all")
    public ShipDataConverter(final ICommandSender sender) {
        this.sender = sender;
    }
}
