// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.network;

import net.minecraft.network.PacketBuffer;
import org.joml.Vector3dc;
import org.valkyrienskies.mod.common.util.JOML;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.UUID;

public final class PlayerMovementData {
    @Nullable
    private final UUID lastTouchedShipId;
    private final int ticksSinceTouchedLastShip;
    private final int ticksPartOfGround;
    @Nonnull
    private final Vector3dc playerPosInShip;
    @Nonnull
    private final Vector3dc playerLookInShip;
    private final boolean onGround;

    /**
     * Reads the raw packet data from the data stream.
     */
    public static PlayerMovementData readData(final PacketBuffer packetBuffer) {
        final boolean hasLastTouchShipId = packetBuffer.readBoolean();
        final UUID lastTouchedShipId = hasLastTouchShipId ? packetBuffer.readUniqueId() : null;
        final int ticksSinceTouchedLastShip = packetBuffer.readInt();
        final int ticksPartOfGround = packetBuffer.readInt();
        final Vector3dc playerPosInShip = JOML.readFromByteBuf(packetBuffer);
        final Vector3dc playerLookInShip = JOML.readFromByteBuf(packetBuffer);
        final boolean onGround = packetBuffer.readBoolean();
        return new PlayerMovementData(lastTouchedShipId, ticksSinceTouchedLastShip, ticksPartOfGround, playerPosInShip, playerLookInShip, onGround);
    }

    /**
     * Writes the raw packet data to the data stream.
     */
    public void writeData(final PacketBuffer packetBuffer) {
        packetBuffer.writeBoolean(lastTouchedShipId != null);
        if (lastTouchedShipId != null) {
            packetBuffer.writeUniqueId(lastTouchedShipId);
        }
        packetBuffer.writeInt(ticksSinceTouchedLastShip);
        packetBuffer.writeInt(ticksPartOfGround);
        JOML.writeToByteBuf(playerPosInShip, packetBuffer);
        JOML.writeToByteBuf(playerLookInShip, packetBuffer);
        packetBuffer.writeBoolean(onGround);
    }

    @java.lang.SuppressWarnings("all")
    public PlayerMovementData(@Nullable final UUID lastTouchedShipId, final int ticksSinceTouchedLastShip, final int ticksPartOfGround, @Nonnull final Vector3dc playerPosInShip, @Nonnull final Vector3dc playerLookInShip, final boolean onGround) {
        if (playerPosInShip == null) {
            throw new java.lang.NullPointerException("playerPosInShip is marked non-null but is null");
        }
        if (playerLookInShip == null) {
            throw new java.lang.NullPointerException("playerLookInShip is marked non-null but is null");
        }
        this.lastTouchedShipId = lastTouchedShipId;
        this.ticksSinceTouchedLastShip = ticksSinceTouchedLastShip;
        this.ticksPartOfGround = ticksPartOfGround;
        this.playerPosInShip = playerPosInShip;
        this.playerLookInShip = playerLookInShip;
        this.onGround = onGround;
    }

    @Nullable
    @java.lang.SuppressWarnings("all")
    public UUID getLastTouchedShipId() {
        return this.lastTouchedShipId;
    }

    @java.lang.SuppressWarnings("all")
    public int getTicksSinceTouchedLastShip() {
        return this.ticksSinceTouchedLastShip;
    }

    @java.lang.SuppressWarnings("all")
    public int getTicksPartOfGround() {
        return this.ticksPartOfGround;
    }

    @Nonnull
    @java.lang.SuppressWarnings("all")
    public Vector3dc getPlayerPosInShip() {
        return this.playerPosInShip;
    }

    @Nonnull
    @java.lang.SuppressWarnings("all")
    public Vector3dc getPlayerLookInShip() {
        return this.playerLookInShip;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isOnGround() {
        return this.onGround;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlayerMovementData)) return false;
        final PlayerMovementData other = (PlayerMovementData) o;
        final java.lang.Object this$lastTouchedShipId = this.getLastTouchedShipId();
        final java.lang.Object other$lastTouchedShipId = other.getLastTouchedShipId();
        if (this$lastTouchedShipId == null ? other$lastTouchedShipId != null : !this$lastTouchedShipId.equals(other$lastTouchedShipId)) return false;
        if (this.getTicksSinceTouchedLastShip() != other.getTicksSinceTouchedLastShip()) return false;
        if (this.getTicksPartOfGround() != other.getTicksPartOfGround()) return false;
        final java.lang.Object this$playerPosInShip = this.getPlayerPosInShip();
        final java.lang.Object other$playerPosInShip = other.getPlayerPosInShip();
        if (this$playerPosInShip == null ? other$playerPosInShip != null : !this$playerPosInShip.equals(other$playerPosInShip)) return false;
        final java.lang.Object this$playerLookInShip = this.getPlayerLookInShip();
        final java.lang.Object other$playerLookInShip = other.getPlayerLookInShip();
        if (this$playerLookInShip == null ? other$playerLookInShip != null : !this$playerLookInShip.equals(other$playerLookInShip)) return false;
        if (this.isOnGround() != other.isOnGround()) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $lastTouchedShipId = this.getLastTouchedShipId();
        result = result * PRIME + ($lastTouchedShipId == null ? 43 : $lastTouchedShipId.hashCode());
        result = result * PRIME + this.getTicksSinceTouchedLastShip();
        result = result * PRIME + this.getTicksPartOfGround();
        final java.lang.Object $playerPosInShip = this.getPlayerPosInShip();
        result = result * PRIME + ($playerPosInShip == null ? 43 : $playerPosInShip.hashCode());
        final java.lang.Object $playerLookInShip = this.getPlayerLookInShip();
        result = result * PRIME + ($playerLookInShip == null ? 43 : $playerLookInShip.hashCode());
        result = result * PRIME + (this.isOnGround() ? 79 : 97);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlayerMovementData(lastTouchedShipId=" + this.getLastTouchedShipId() + ", ticksSinceTouchedLastShip=" + this.getTicksSinceTouchedLastShip() + ", ticksPartOfGround=" + this.getTicksPartOfGround() + ", playerPosInShip=" + this.getPlayerPosInShip() + ", playerLookInShip=" + this.getPlayerLookInShip() + ", onGround=" + this.isOnGround() + ")";
    }
}
