package zmaster587.advancedRocketry.space;

import zmaster587.advancedRocketry.world.provider.WorldProviderSpace;

/**
 * Pool-slot space world provider: a reusable empty-space world whose ON-DISK chunk
 * directory is chosen by the CELL currently bound to this slot, not by the dimension id.
 *
 * <p>One pre-registered "slot" dimension can therefore host different logical space cells
 * over time: {@code AnvilSaveHandler.getChunkLoader} builds the chunk loader from
 * {@link #getSaveFolder()}, so returning the bound cell's folder here retargets where this
 * world reads and writes chunks. Rebinding a slot to another cell (see {@link SpaceSlotPool})
 * flushes, changes the binding, and reinitialises the dimension so the loader is rebuilt
 * against the new folder. Empty space is generated by the inherited
 * {@link WorldProviderSpace} (void by default).</p>
 */
public class WorldProviderSpaceSlot extends WorldProviderSpace {

    @Override
    public String getSaveFolder() {
        String cell = SpaceSlotPool.cellKeyFor(getDimension());
        // Unbound slot -> a private per-slot scratch folder; bound -> the cell's shared folder
        // (two slots must never bind the same cell simultaneously -- the pool enforces that).
        return cell == null
                ? "advRocketry/spacepool/slot" + getDimension()
                : "advRocketry/spacepool/cell_" + cell;
    }
}
