// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships.physics_data;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.joml.Vector3d;
import org.joml.Vector3dc;

/**
 * Stores data used by {@link org.valkyrienskies.mod.common.physics.PhysicsCalculations}
 */
public class ShipPhysicsData {
    @JsonSerialize(as = Vector3d.class)
    @JsonDeserialize(as = Vector3d.class)
    private Vector3dc linearVelocity;
    @JsonSerialize(as = Vector3d.class)
    @JsonDeserialize(as = Vector3d.class)
    private Vector3dc angularVelocity;

    @java.lang.SuppressWarnings("all")
    public Vector3dc getLinearVelocity() {
        return this.linearVelocity;
    }

    @java.lang.SuppressWarnings("all")
    public Vector3dc getAngularVelocity() {
        return this.angularVelocity;
    }

    @java.lang.SuppressWarnings("all")
    public void setLinearVelocity(final Vector3dc linearVelocity) {
        this.linearVelocity = linearVelocity;
    }

    @java.lang.SuppressWarnings("all")
    public void setAngularVelocity(final Vector3dc angularVelocity) {
        this.angularVelocity = angularVelocity;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ShipPhysicsData)) return false;
        final ShipPhysicsData other = (ShipPhysicsData) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$linearVelocity = this.getLinearVelocity();
        final java.lang.Object other$linearVelocity = other.getLinearVelocity();
        if (this$linearVelocity == null ? other$linearVelocity != null : !this$linearVelocity.equals(other$linearVelocity)) return false;
        final java.lang.Object this$angularVelocity = this.getAngularVelocity();
        final java.lang.Object other$angularVelocity = other.getAngularVelocity();
        if (this$angularVelocity == null ? other$angularVelocity != null : !this$angularVelocity.equals(other$angularVelocity)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ShipPhysicsData;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $linearVelocity = this.getLinearVelocity();
        result = result * PRIME + ($linearVelocity == null ? 43 : $linearVelocity.hashCode());
        final java.lang.Object $angularVelocity = this.getAngularVelocity();
        result = result * PRIME + ($angularVelocity == null ? 43 : $angularVelocity.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ShipPhysicsData(linearVelocity=" + this.getLinearVelocity() + ", angularVelocity=" + this.getAngularVelocity() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ShipPhysicsData(final Vector3dc linearVelocity, final Vector3dc angularVelocity) {
        this.linearVelocity = linearVelocity;
        this.angularVelocity = angularVelocity;
    }

    @java.lang.SuppressWarnings("all")
    public ShipPhysicsData() {
    }
}
