// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships.physics_data;

import org.joml.Matrix3d;
import org.joml.Matrix3dc;
import org.joml.Vector3d;
import org.joml.Vector3dc;
import javax.annotation.Nonnull;

/**
 * Stores the data of the ship mas and inertia matrix.
 */
public class ShipInertiaData {
    double gameTickMass = 0;
    @Nonnull
    Matrix3dc gameMoITensor = new Matrix3d();
    @Nonnull
    Vector3dc gameTickCenterOfMass = new Vector3d();

    @java.lang.SuppressWarnings("all")
    public ShipInertiaData() {
    }

    @java.lang.SuppressWarnings("all")
    public double getGameTickMass() {
        return this.gameTickMass;
    }

    @Nonnull
    @java.lang.SuppressWarnings("all")
    public Matrix3dc getGameMoITensor() {
        return this.gameMoITensor;
    }

    @Nonnull
    @java.lang.SuppressWarnings("all")
    public Vector3dc getGameTickCenterOfMass() {
        return this.gameTickCenterOfMass;
    }

    @java.lang.SuppressWarnings("all")
    public void setGameTickMass(final double gameTickMass) {
        this.gameTickMass = gameTickMass;
    }

    @java.lang.SuppressWarnings("all")
    public void setGameMoITensor(@Nonnull final Matrix3dc gameMoITensor) {
        if (gameMoITensor == null) {
            throw new java.lang.NullPointerException("gameMoITensor is marked non-null but is null");
        }
        this.gameMoITensor = gameMoITensor;
    }

    @java.lang.SuppressWarnings("all")
    public void setGameTickCenterOfMass(@Nonnull final Vector3dc gameTickCenterOfMass) {
        if (gameTickCenterOfMass == null) {
            throw new java.lang.NullPointerException("gameTickCenterOfMass is marked non-null but is null");
        }
        this.gameTickCenterOfMass = gameTickCenterOfMass;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ShipInertiaData)) return false;
        final ShipInertiaData other = (ShipInertiaData) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getGameTickMass(), other.getGameTickMass()) != 0) return false;
        final java.lang.Object this$gameMoITensor = this.getGameMoITensor();
        final java.lang.Object other$gameMoITensor = other.getGameMoITensor();
        if (this$gameMoITensor == null ? other$gameMoITensor != null : !this$gameMoITensor.equals(other$gameMoITensor)) return false;
        final java.lang.Object this$gameTickCenterOfMass = this.getGameTickCenterOfMass();
        final java.lang.Object other$gameTickCenterOfMass = other.getGameTickCenterOfMass();
        if (this$gameTickCenterOfMass == null ? other$gameTickCenterOfMass != null : !this$gameTickCenterOfMass.equals(other$gameTickCenterOfMass)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ShipInertiaData;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $gameTickMass = java.lang.Double.doubleToLongBits(this.getGameTickMass());
        result = result * PRIME + (int) ($gameTickMass >>> 32 ^ $gameTickMass);
        final java.lang.Object $gameMoITensor = this.getGameMoITensor();
        result = result * PRIME + ($gameMoITensor == null ? 43 : $gameMoITensor.hashCode());
        final java.lang.Object $gameTickCenterOfMass = this.getGameTickCenterOfMass();
        result = result * PRIME + ($gameTickCenterOfMass == null ? 43 : $gameTickCenterOfMass.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ShipInertiaData(gameTickMass=" + this.getGameTickMass() + ", gameMoITensor=" + this.getGameMoITensor() + ", gameTickCenterOfMass=" + this.getGameTickCenterOfMass() + ")";
    }
}
