package zmaster587.advancedRocketry.event;

import net.minecraft.world.World;
import net.minecraft.world.storage.DerivedWorldInfo;
import net.minecraft.world.storage.WorldInfo;
import net.minecraftforge.event.world.WorldEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import zmaster587.advancedRocketry.world.CustomDerivedWorldInfo;
import zmaster587.advancedRocketry.world.provider.WorldProviderPlanet;

public class WorldInfoHandler {
    @SubscribeEvent
    public void injectCustomWorldInfo(WorldEvent.Load event) {
        World world = event.getWorld();
        if (world.isRemote) return;
        // Only inject world info into planets generated by AR
        if (!(world.provider instanceof WorldProviderPlanet)) return;

        CustomDerivedWorldInfo customInfo = new CustomDerivedWorldInfo(world);
        WorldInfo existingInfo = world.getWorldInfo();
        if (existingInfo.getClass() == DerivedWorldInfo.class) {
            // Completely override the world info
            world.worldInfo = customInfo;
        } else if (!(existingInfo instanceof CustomDerivedWorldInfo)) {
            // Inject the raw properties into the world info
            customInfo.injectWeatherData(existingInfo);
        }
    }
}
