// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.command.config;

import javax.annotation.Nullable;
import java.lang.reflect.Field;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Node at the end of a config command, e.g. in <code>/vsc enginePower basicEngineForce</code>,
 * <code>basicEngineForce</code> is the End Node
 */
class ConfigCommandEndNode extends ConfigCommandNode {
    private final Consumer<String> optionSetter;
    private final Supplier<?> optionGetter;
    private final List<String> autocompletions;

    ConfigCommandEndNode(Field field, @Nullable Object object) {
        this(getName(field), str -> ConfigCommandUtils.setFieldFromString(str, field, object), () -> ConfigCommandUtils.getStringFromField(field, object), ConfigCommandUtils.getAutocompletions(field));
    }

    private static String getName(Field field) {
        return Optional.ofNullable(field.getAnnotation(ShortName.class)).map(ShortName::value).orElseGet(field::getName);
    }

    ConfigCommandEndNode(String name, Consumer<String> optionSetter, Supplier<?> getOption, List<String> autocompletions) {
        super(name);
        this.optionSetter = optionSetter;
        this.optionGetter = getOption;
        this.autocompletions = autocompletions;
    }

    @java.lang.SuppressWarnings("all")
    public Consumer<String> getOptionSetter() {
        return this.optionSetter;
    }

    @java.lang.SuppressWarnings("all")
    public Supplier<?> getOptionGetter() {
        return this.optionGetter;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getAutocompletions() {
        return this.autocompletions;
    }
}
