// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.command.config;

abstract class ConfigCommandNode {
    private String name;

    ConfigCommandNode(String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }
}
